# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of a product category')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date product was added to database')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date customer added to database')),
                ('name', models.TextField(help_text='Name of the customer')),
                ('primary_phone', models.CharField(blank=True, help_text='Phone number of the customer', max_length=25)),
                ('secondary_phone', models.CharField(blank=True, help_text='Phone number of the customer', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of creation of the invoice')),
                ('credit', models.BooleanField(default=False, help_text='Credit sale')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Quantity sold')),
                ('sell_price', models.DecimalField(decimal_places=3, default=0.0, help_text='Sell price at time of sale', max_digits=7)),
                ('cost_price', models.DecimalField(decimal_places=3, default=0.0, help_text='Cost price at time of sale', max_digits=7)),
                ('returned_quantity', models.IntegerField(default=0, help_text='Quantity returned by customer')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the product')),
                ('description', models.TextField(blank=True, help_text='Description of the product')),
                ('size', models.TextField(blank=True, help_text='Size of the product')),
                ('cost_price', models.DecimalField(decimal_places=3, default=0.0, help_text='Cost price of the product', max_digits=7)),
                ('sell_price', models.DecimalField(decimal_places=3, default=0.0, help_text='Sell price of the product', max_digits=7)),
                ('stock', models.IntegerField(default=0, help_text='Quantity of the product in stock')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date product was added to database')),
                ('image', models.ImageField(blank=True, help_text='An image of the product', null=True, upload_to='')),
                ('hide_product', models.BooleanField(default=False, help_text='Hide from list of available products')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of a country and/or city')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date product was added to database')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.TextField(help_text='Name of the supplier')),
                ('agent', models.TextField(blank=True, help_text='Name of the company agent')),
                ('email', models.EmailField(blank=True, help_text='Email address of the supplier', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the supplier', max_length=25)),
                ('address', models.TextField(blank=True, help_text='Address of the supplier')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Source'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Supplier'),
        ),
        migrations.AddField(
            model_name='invoiceproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='database.Product'),
        ),
    ]
