# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20170806_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date product was added to database'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date customer added to database'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of creation of the invoice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date product was added to database'),
        ),
        migrations.AlterField(
            model_name='source',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date product was added to database'),
        ),
    ]
