# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20170820_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='Phone number of the customer', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='secondary_phone',
            field=models.CharField(blank=True, help_text='Phone number of the customer', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, help_text='Size of the product', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, help_text='Address of the supplier', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='agent',
            field=models.TextField(blank=True, help_text='Name of the company agent', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the supplier', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the supplier', max_length=25, null=True),
        ),
    ]
