# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-20 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20170820_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(help_text='Name of a product category', unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.TextField(help_text='Name of the customer', unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(help_text='Name of a country and/or city', unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set([('name', 'description', 'size', 'supplier')]),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together=set([('company', 'agent')]),
        ),
    ]
