# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20170820_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_of_sale',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of sale for the invoice'),
        ),
    ]
