# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_invoice_date_of_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceproduct',
            name='quantity',
            field=models.IntegerField(help_text='Quantity sold'),
        ),
        migrations.AlterField(
            model_name='invoiceproduct',
            name='sell_price',
            field=models.DecimalField(decimal_places=3, help_text='Sell price at time of sale', max_digits=7),
        ),
    ]
