# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20171210_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCreditPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.DecimalField(decimal_places=3, help_text='Credit payment for this invoice', max_digits=7)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_payments', to='database.Invoice')),
            ],
        ),
    ]
