# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_invoicecreditpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecreditpayment',
            name='date_of_payment',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date of credit payment'),
        ),
    ]
