# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_invoicecreditpayment_date_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='database.Supplier'),
        ),
    ]
