# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-03 03:08
from __future__ import unicode_literals

import database.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20180218_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_sort',
            field=database.models.NaturalSortField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_sort',
            field=database.models.NaturalSortField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size_sort',
            field=database.models.NaturalSortField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
