# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20180503_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='database.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='database.Source'),
        ),
    ]
